dist: xenial
language: python

cache:
  pip: true

before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - pip install codecov

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - --preview
  - source $HOME/.poetry/env
  - pip install tox -U

script:
  - tox

matrix:
  fast_finish: true
  include:
    # lint
    - python: "3.7"
      stage: lint
      env: TOXENV=lint

    # test
    - python: "3.6.5"
      stage: test
      env: TOXENV=py36
    - python: "3.7.1"
      stage: test
      env: TOXENV=py37

after_script:
  - ./cc-test-reporter format-coverage --input-type coverage.py
  - ./cc-test-reporter sum-coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - codecov

notification:
  email: false
